#!/bin/bash
# "INSTALL bare" installs a bare repository on the base machine
# "INSTALL" with no argument to source vw/profile in .bashrc

pushd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null
VW_DIR="$PWD"

if test "$1" = "bare" 
then # create bare repository
    (
    cd
    mkdir -p git_root
    cp -a $VW_DIR/.git git_root/vw.git
    cd git_root/vw.git
    git config --bool core.bare true
    # show connection info for downstream copies
    echo Use following to get downstream clone:
    echo git clone $(id -un)@$(hostname):git_root/vw.git
    )
else # add line to .bashrc to source vw profile
    (
    cd
    B=.bashrc
    test -s $B || echo > $B
    grep -v '^source .*/profile.$' $B > $B.tmp
    echo "source '$VW_DIR/profile'" >> $B.tmp
    cmp -s $B $B.tmp || mv -v $B $B.bak
    mv $B.tmp $B
    )
fi
